# Generated by Django 3.2.4 on 2021-10-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitle', models.CharField(max_length=100)),
                ('sdes', models.TextField(max_length=5600)),
                ('spic', models.ImageField(default='', upload_to='static/slider')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.CharField(max_length=500)),
                ('vtitle', models.CharField(max_length=500)),
                ('vdate', models.DateField()),
            ],
        ),
    ]
